services:
  neo4j:
    image: neo4j:5.19-bullseye
    container_name: neo4j
    ports:
#      UI
      - "7474:7474"
#      CONNECT PORT
      - "7687:7687"
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_memory_pagecache_size=1G
      - NEO4J_dbms_memory_heap_max__size=2G
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/import
      - ./neo4j/plugins:/plugins